### ISSUE TITLE
Was ganz anderes (warnapp)

### ISSUE THREAD

**Issue by S60W79** [Venji10/fmradio-volla#2]
Tut mir leid, das ich Sie hier anschreiben muss, aber der Openstore hat keine Antworten-funktion.
Kannst du mir bitte die Fehlermeldungen der Warnapp beim Starten schicken?
Du bekommst sie nach einem Crash mit der App Logviewer im entsprechenden eintrag.
Du kannst auch den Eintrag "ubuntu-push-client" ansehen, dort kann der Fehler auch liegen.
Am besten schicke mir beide Einträge als Antwort auf diesen Issue oder mache einen neuen Issue im Repo der warnapp auf (link im Openstore unter
technische Unterstützung).
Vlt. finde ich so den Fehler.
LG

**Comment by Fuseteam** [comment]
@S60W79 who are you writing to? which openstore bug report are your replying to? this repository is about an fmradio for the vollaphone

**Comment by Danfro** [comment]
@S60W79 falls du Enrico anschreiben willst, der ist in diversen Ubuntu Touch Telegram Gruppen aktiv. Handle: @Anleitungdab. Zum Beispiel in der englischen Hauptgruppe https://t.me/ubports. 

Ansonsten wird das hier glaube ich ohne ein Tag nicht funktionieren.

**Comment by S60W79** [comment]
Oh, I am Sorry, maybe I wrote to the wrong repo.
I tried to contact the github/UT user 1978Enrico, concerning his bug report
on the openstore.
If you know his contact data however write him, to open an Issue on
https://github.com/S60W79/warnapp-deutschland/issues
Greetings

Am Fr., 10. Dez. 2021 um 13:55 Uhr schrieb Rahammetoela Toekiman <
***@***.***>:

**Comment by Fuseteam** [comment]
ah i see, have you seen danfro's reply? he has linked the contact information for 1978enrico. if you have seen that reply, feel free to close this issue
i'll send him to your repo too

**Comment by S60W79** [comment]
> "ubuntu-push-client

Thank you very much for your help, I successfully contacted him.
You're great community (;
Greetings
